# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      sudo apt install rsync --assume-yes
      sudo add-apt-repository -y ppa:ethereum/ethereum
      sudo apt-get update --assume-yes
      sudo apt-get install ethereum --assume-yes
      
      mkdir $HOME/Downloads
      wget https://github.com/rsksmart/rskj/releases/download/IRIS-3.0.1/rskj-core-3.0.1-IRIS-all.jar -P $HOME/Downloads

      mkdir ~/.boltz
      cp boltz.gitpod.conf ~/.boltz/boltz.conf
    command: yarn rsk:geth
  - command: yarn docker:regtest  
  - command: geth --exec 'loadScript("deploy_contract_geth.js")' attach http://127.0.0.1:4444/
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9001
    visibility: public
